import sqlite3
import os

conn = sqlite3.connect("application/sqlite3.db")
cursor = conn.cursor()

cursor.execute("""
    CREATE TABLE IF NOT EXISTS players (
        first_and_second_name VARCHAR(100) NOT NULL PRIMARY KEY,
        date_of_born DATE NOT NULL,
        gender VARCHAR(9) NOT NULL
    )
""")

cursor.execute("""
    CREATE TABLE IF NOT EXISTS comands (
        name_of_team VARCHAR(50) NOT NULL,
        name_of_game VARCHAR(200) NOT NULL,
        date_of_game DATE NOT NULL,
        first_and_second_name_1 VARCHAR(100) NOT NULL,
        first_and_second_name_2 VARCHAR(100) NOT NULL,
        first_and_second_name_3 VARCHAR(100),
        first_and_second_name_4 VARCHAR(100),
        first_and_second_name_5 VARCHAR(100),
        
        one_1 INT,
        two_1 INT,
        three_1 INT,
        four_1 INT,
        five_1 INT,
        six_1 INT,
        seven_1 INT,
        eight_1 INT,
        nine_1 INT,
        one_zero_1 INT,
        one_one_1 INT,
        one_two_1 INT,
        one_three_1 INT,
        one_four_1 INT,
        one_five_1 INT,
        one_six_1 INT,
        one_seven_1 INT,
        one_eight_1 INT,
        one_nine_1 INT,
        two_zero_1 INT,
        two_one_1 INT,
        two_two_1 INT,
        two_three_1 INT,
        two_four_1 INT,
        two_five_1 INT,
        two_six_1 INT,
        two_seven_1 INT,
        two_eight_1 INT,
        two_nine_1 INT,
        three_zero_1 INT,
        extra_one_1 INT,
        extra_two_1 INT,
        extra_three_1 INT,
        extra_four_1 INT,
        extra_five_1 INT,
        extra_six_1 INT,
        extra_seven_1 INT,
        extra_eight_1 INT,
        extra_nine_1 INT,
        points_1 INT,
        final_percentage_1 FLOAT,
        
        one_2 INT,
        two_2 INT,
        three_2 INT,
        four_2 INT,
        five_2 INT,
        six_2 INT,
        seven_2 INT,
        eight_2 INT,
        nine_2 INT,
        one_zero_2 INT,
        one_one_2 INT,
        one_two_2 INT,
        one_three_2 INT,
        one_four_2 INT,
        one_five_2 INT,
        one_six_2 INT,
        one_seven_2 INT,
        one_eight_2 INT,
        one_nine_2 INT,
        two_zero_2 INT,
        two_one_2 INT,
        two_two_2 INT,
        two_three_2 INT,
        two_four_2 INT,
        two_five_2 INT,
        two_six_2 INT,
        two_seven_2 INT,
        two_eight_2 INT,
        two_nine_2 INT,
        three_zero_2 INT,
        extra_one_2 INT,
        extra_two_2 INT,
        extra_three_2 INT,
        extra_four_2 INT,
        extra_five_2 INT,
        extra_six_2 INT,
        extra_seven_2 INT,
        extra_eight_2 INT,
        extra_nine_2 INT,
        points_2 INT,
        final_percentage_2 FLOAT,
        
        one_3 INT,
        two_3 INT,
        three_3 INT,
        four_3 INT,
        five_3 INT,
        six_3 INT,
        seven_3 INT,
        eight_3 INT,
        nine_3 INT,
        one_zero_3 INT,
        one_one_3 INT,
        one_two_3 INT,
        one_three_3 INT,
        one_four_3 INT,
        one_five_3 INT,
        one_six_3 INT,
        one_seven_3 INT,
        one_eight_3 INT,
        one_nine_3 INT,
        two_zero_3 INT,
        extra_one_3 INT,
        extra_two_3 INT,
        extra_three_3 INT,
        extra_four_3 INT,
        extra_five_3 INT,
        extra_six_3 INT,
        points_3 INT,
        final_percentage_3 FLOAT,
        
        one_4 INT,
        two_4 INT,
        three_4 INT,
        four_4 INT,
        five_4 INT,
        six_4 INT,
        seven_4 INT,
        eight_4 INT,
        nine_4 INT,
        one_zero_4 INT,
        one_one_4 INT,
        one_two_4 INT,
        one_three_4 INT,
        one_four_4 INT,
        one_five_4 INT,
        one_six_4 INT,
        one_seven_4 INT,
        one_eight_4 INT,
        one_nine_4 INT,
        two_zero_4 INT,
        extra_one_4 INT,
        extra_two_4 INT,
        extra_three_4 INT,
        extra_four_4 INT,
        extra_five_4 INT,
        extra_six_4 INT,
        points_4 INT,
        final_percentage_4 FLOAT,
        
        one_5 INT,
        two_5 INT,
        three_5 INT,
        four_5 INT,
        five_5 INT,
        six_5 INT,
        seven_5 INT,
        eight_5 INT,
        nine_5 INT,
        one_zero_5 INT,
        one_one_5 INT,
        one_two_5 INT,
        one_three_5 INT,
        one_four_5 INT,
        one_five_5 INT,
        one_six_5 INT,
        one_seven_5 INT,
        one_eight_5 INT,
        one_nine_5 INT,
        two_zero_5 INT,
        extra_one_5 INT,
        extra_two_5 INT,
        extra_three_5 INT,
        extra_four_5 INT,
        extra_five_5 INT,
        extra_six_5 INT,
        points_5 INT,
        final_percentage_5 FLOAT

    )
""")

def path_db ():
    current_dir = os.path.dirname(os.path.abspath(__file__))
    db_path = os.path.join(current_dir, "sqlite3.db")
    return db_path

def inp_filter(text, *args):
    max_length = 3
    
    if len(text) <= max_length and text in "012":
        return text
    else:
        return ''
