[tool.poetry]
name = "application"
version = "0.1.0"
description = ""
authors = ["Sergey Borovikov <boborovikov@yandex.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
kivy = {extras = ["base"], version = "^2.3.0"}
pylance = "^0.16.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
